const sdk = require('cos-grpc-js')

const priv = sdk.crypto.privKeyFromWIF('4DjYx2KAGh1NP3dai7MZTLUBMMhMBPmwouKE8jhVSESywccpVZ');
const pub = priv.pubKey();
const auth = new sdk.raw_type.authority();
const pub_key_type = new sdk.raw_type.public_key_type();
pub_key_type.setData(pub.data);
auth.setKey(pub_key_type);
const acop = new sdk.operation.account_create_operation();
const c = new sdk.raw_type.coin();
c.setValue(1);
acop.setFee(c);
const creator = new sdk.raw_type.account_name();
creator.setValue("initminer");
acop.setCreator(creator);
const an = new sdk.raw_type.account_name();
an.setValue("kochiya");
acop.setNewAccountName(an);
acop.setOwner(auth);
const tx = new sdk.transaction.transaction();
tx.setRefBlockNum(0);
tx.setRefBlockNum(0);
const time = new sdk.raw_type.time_point_sec();
time.setUtcSeconds(30);
tx.setExpiration(time);
tx.addOperation(acop);
const signTx = new sdk.transaction.signed_transaction();
signTx.setTrx(tx);
const signature = new sdk.raw_type.signature_type();
let s = signTx.sign(priv);
console.log(s);
